# Generated by Django 3.1.6 on 2021-02-11 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.CharField(max_length=200)),
                ('name', models.DateTimeField(verbose_name='date published')),
                ('imageURL', models.CharField(max_length=200)),
                ('manaCost', models.CharField(max_length=100)),
                ('loyalty', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=10)),
                ('toughness', models.CharField(max_length=10)),
                ('typeLine', models.CharField(max_length=500)),
                ('colorId', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=500)),
                ('twoFace', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=50)),
                ('imageURL', models.CharField(max_length=200)),
                ('isMana', models.BooleanField()),
                ('manaCost', models.CharField(max_length=10)),
                ('colorID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('comment', models.CharField(max_length=500)),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collection.card')),
            ],
        ),
        migrations.CreateModel(
            name='Lagality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.BooleanField()),
                ('future', models.BooleanField()),
                ('historic', models.BooleanField()),
                ('gladiator', models.BooleanField()),
                ('modern', models.BooleanField()),
                ('legacy', models.BooleanField()),
                ('pauper', models.BooleanField()),
                ('vintage', models.BooleanField()),
                ('penny', models.BooleanField()),
                ('commander', models.BooleanField()),
                ('brawl', models.BooleanField()),
                ('duel', models.BooleanField()),
                ('oldSchool', models.BooleanField()),
                ('premodern', models.BooleanField()),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collection.card')),
            ],
        ),
    ]
