# Generated by Django 3.1.7 on 2021-03-21 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=200)),
                ('oracle_id', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=500)),
                ('rarity', models.CharField(max_length=20)),
                ('set_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CardIDList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=200)),
                ('oracle_id', models.CharField(max_length=200)),
                ('card_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(max_length=30)),
                ('sides', models.IntegerField()),
                ('multi_face', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardSets',
            fields=[
                ('set_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('released_at', models.DateField(default=datetime.datetime.now)),
                ('icon_svg_uri', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IgnoreCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracle_id', models.CharField(max_length=200)),
                ('pub_date', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=200)),
                ('is_mana', models.CharField(max_length=20)),
                ('mana_cost', models.CharField(max_length=20, null=True)),
                ('color_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Legality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=15)),
                ('future', models.CharField(max_length=15)),
                ('historic', models.CharField(max_length=15)),
                ('gladiator', models.CharField(max_length=15)),
                ('modern', models.CharField(max_length=15)),
                ('legacy', models.CharField(max_length=15)),
                ('pauper', models.CharField(max_length=15)),
                ('vintage', models.CharField(max_length=15)),
                ('penny', models.CharField(max_length=15)),
                ('commander', models.CharField(max_length=15)),
                ('brawl', models.CharField(max_length=15)),
                ('duel', models.CharField(max_length=15)),
                ('old_school', models.CharField(max_length=15)),
                ('premodern', models.CharField(max_length=15)),
                ('oracle_id', models.CharField(max_length=200)),
                ('card_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_card', to='Collection.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('mana_cost', models.CharField(max_length=100)),
                ('loyalty', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=10)),
                ('toughness', models.CharField(max_length=10)),
                ('type_line', models.CharField(max_length=500)),
                ('color_id', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('flavor_text', models.CharField(max_length=500)),
                ('card_id', models.CharField(max_length=200)),
                ('oracle_id', models.CharField(max_length=200)),
                ('avatar_img', models.CharField(max_length=200)),
                ('first_face', models.BooleanField()),
                ('legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_legal', to='Collection.legality')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_layout', to='Collection.cardlayout'),
        ),
        migrations.AddField(
            model_name='card',
            name='set_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_set', to='Collection.cardsets'),
        ),
    ]
