# Generated by Django 3.1.7 on 2021-03-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_layout', to='Collection.cardlayout'),
        ),
        migrations.AlterField(
            model_name='card',
            name='set_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_set', to='Collection.cardsets'),
        ),
    ]
