# Generated by Django 3.1.6 on 2021-02-13 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lagality',
            new_name='Legality',
        ),
        migrations.RemoveField(
            model_name='card',
            name='colorId',
        ),
        migrations.RemoveField(
            model_name='card',
            name='imageURL',
        ),
        migrations.RemoveField(
            model_name='card',
            name='loyalty',
        ),
        migrations.RemoveField(
            model_name='card',
            name='manaCost',
        ),
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='power',
        ),
        migrations.RemoveField(
            model_name='card',
            name='toughness',
        ),
        migrations.RemoveField(
            model_name='card',
            name='twoFace',
        ),
        migrations.RemoveField(
            model_name='card',
            name='typeLine',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='cardID',
        ),
        migrations.AddField(
            model_name='card',
            name='oracleID',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='oracleID',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='Collection.card'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CardFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateTimeField(verbose_name='date published')),
                ('imageURL', models.CharField(max_length=200)),
                ('manaCost', models.CharField(max_length=100)),
                ('loyalty', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=10)),
                ('toughness', models.CharField(max_length=10)),
                ('typeLine', models.CharField(max_length=500)),
                ('colorId', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('flavorText', models.CharField(max_length=500)),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collection.card')),
            ],
        ),
    ]
