# Generated by Django 3.1.7 on 2021-03-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0002_auto_20210321_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='cardface',
            name='legal',
        ),
        migrations.RemoveField(
            model_name='legality',
            name='card_obj',
        ),
    ]
