# Generated by Django 3.1.6 on 2021-02-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Collection', '0002_auto_20210212_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardface',
            name='cardID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='legality',
            name='cardID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rule',
            name='oracleID',
            field=models.CharField(max_length=200),
        ),
    ]
