# Generated by Django 3.1.7 on 2021-03-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Collection', '0003_auto_20210321_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='card_layout', to='Collection.cardlayout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardface',
            name='legal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='face_legal',
                                    to='Collection.legality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legality',
            name='card_obj',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='legal_card',
                                    to='Collection.card'),
            preserve_default=False,
        ),
    ]
