# Generated by Django 3.1.6 on 2021-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0003_auto_20210212_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardface',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='legality',
            name='brawl',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='commander',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='duel',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='future',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='gladiator',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='historic',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='legacy',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='modern',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='oldSchool',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='pauper',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='penny',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='premodern',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='standard',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='legality',
            name='vintage',
            field=models.CharField(max_length=15),
        ),
    ]
