# Generated by Django 3.1.6 on 2021-02-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Collection', '0004_auto_20210218_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='pub_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='isMana',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='manaCost',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
