# Generated by Django 3.1.6 on 2021-02-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Collection', '0005_auto_20210218_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='manaCost',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
