# Generated by Django 3.1.7 on 2021-03-24 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Collection', '0006_auto_20210323_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='colorId',
            new_name='color_id',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='isPreCon',
            new_name='is_pre_con',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='isPrivate',
            new_name='is_private',
        ),
    ]
