# Generated by Django 3.1.6 on 2021-02-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0007_auto_20210219_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(default='common', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='setName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
