# Generated by Django 3.1.7 on 2021-03-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Collection', '0007_auto_20210323_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='decktype',
            name='card_copy_limit',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='decktype',
            name='has_commander',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decktype',
            name='max_deck_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decktype',
            name='min_deck_size',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='decktype',
            name='side_board_size',
            field=models.IntegerField(default=15),
        ),
    ]
