# Generated by Django 3.1.6 on 2021-02-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0008_auto_20210220_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardface',
            name='duelFace',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
