# Generated by Django 3.1.6 on 2021-02-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Collection', '0009_cardface_duelface'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
