# Generated by Django 3.1.6 on 2021-02-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0010_ignorecards'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.CharField(default='normal', max_length=30),
            preserve_default=False,
        ),
    ]
