# Generated by Django 3.1.7 on 2021-03-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0010_auto_20210324_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardface',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
