# Generated by Django 3.1.6 on 2021-02-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0011_card_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(max_length=30)),
            ],
        ),
    ]
