# Generated by Django 3.1.7 on 2021-03-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0012_deck_deck_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardface',
            name='image_file',
            field=models.ImageField(null=True, upload_to='static/img/cards'),
        ),
    ]
