# Generated by Django 3.1.7 on 2021-04-01 02:27

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0013_auto_20210329_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardface',
            name='image_file',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
