# Generated by Django 3.1.6 on 2021-02-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0013_cardlayout_sides'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardface',
            old_name='duelFace',
            new_name='firstFace',
        ),
    ]
