# Generated by Django 3.1.7 on 2021-02-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0014_auto_20210222_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlayout',
            name='multiFace',
            field=models.IntegerField(default=0, verbose_name=1),
            preserve_default=False,
        ),
    ]
