# Generated by Django 3.1.7 on 2021-04-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0014_auto_20210331_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardface',
            name='image_file',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
