# Generated by Django 3.1.7 on 2021-04-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0015_auto_20210331_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardface',
            name='avatar_file',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
