# Generated by Django 3.1.7 on 2021-02-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0015_cardlayout_multiface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlayout',
            name='multiFace',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cardlayout',
            name='sides',
            field=models.IntegerField(),
        ),
    ]
