# Generated by Django 3.1.7 on 2021-02-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0016_auto_20210223_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardface',
            name='avatarImg',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
