# Generated by Django 3.1.7 on 2021-04-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0016_cardface_avatar_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='commander',
        ),
        migrations.RemoveField(
            model_name='deckcards',
            name='card',
        ),
        migrations.AddField(
            model_name='cardface',
            name='card_search',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='commander_file',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='commander_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='commander_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='commander_oracle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deckcards',
            name='card_oracle',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deckcards',
            name='card_search',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
