# Generated by Django 3.1.7 on 2021-02-28 22:34

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Collection', '0017_cardface_avatarimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSets',
            fields=[
                ('set_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('released_at', models.DateField(default=datetime.datetime.now)),
                ('icon_svg_uri', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='setOrder',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardface',
            name='setOrder',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
