# Generated by Django 3.1.7 on 2021-04-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0017_auto_20210401_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcards',
            name='card_file',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
