# Generated by Django 3.1.7 on 2021-03-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0018_auto_20210228_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardIDList',
            fields=[
                ('cardID', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
