# Generated by Django 3.1.7 on 2021-04-04 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0021_auto_20210403_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsets',
            name='released_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quickresult',
            name='last_update',
            field=models.DateField(default=datetime.date(2021, 4, 4)),
        ),
        migrations.AlterField(
            model_name='quickresult',
            name='result',
            field=models.CharField(default='{}', max_length=2000000),
        ),
    ]
