# Generated by Django 3.1.7 on 2021-04-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0022_auto_20210404_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickresult',
            name='result',
            field=models.TextField(default='{}'),
        ),
    ]
