# Generated by Django 3.1.7 on 2021-04-13 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0023_auto_20210404_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckcards',
            name='deck',
        ),
        migrations.AlterField(
            model_name='quickresult',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 4, 12, 20, 43, 15, 843213)),
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.DeleteModel(
            name='DeckCards',
        ),
        migrations.DeleteModel(
            name='DeckType',
        ),
    ]
