# Generated by Django 3.1.7 on 2021-04-14 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0024_auto_20210412_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickresult',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 4, 13, 21, 9, 59, 927223)),
        ),
    ]
