# Generated by Django 3.1.7 on 2021-04-15 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0027_auto_20210414_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardidlist',
            name='tcg_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardidlist',
            name='tcg_price_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 23, 31, 34, 586180)),
        ),
        migrations.AlterField(
            model_name='quickresult',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 23, 31, 34, 588181)),
        ),
    ]
