# Generated by Django 3.1.7 on 2021-04-18 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0029_auto_20210414_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardface',
            name='legal',
        ),
        migrations.RemoveField(
            model_name='legality',
            name='card_obj',
        ),
        migrations.AlterField(
            model_name='cardidlist',
            name='tcg_price_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 17, 21, 45, 13, 771586)),
        ),
        migrations.AlterField(
            model_name='quickresult',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 4, 17, 21, 45, 13, 772588)),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='CardFace',
        ),
        migrations.DeleteModel(
            name='CardLayout',
        ),
        migrations.DeleteModel(
            name='CardSets',
        ),
        migrations.DeleteModel(
            name='Legality',
        ),
    ]
