# Generated by Django 3.1.7 on 2021-04-19 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0030_auto_20210417_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardidlist',
            name='tcg_price_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 17, 17, 9, 633125)),
        ),
        migrations.AlterField(
            model_name='quickresult',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 17, 17, 9, 634124)),
        ),
    ]
