# Generated by Django 3.1.7 on 2021-04-20 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0031_auto_20210419_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardidlist',
            name='tcg_price_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 20, 20, 8, 693773)),
        ),
        migrations.AlterField(
            model_name='quickresult',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 20, 20, 8, 694771)),
        ),
    ]
