# Generated by Django 3.1.7 on 2021-04-21 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0033_auto_20210420_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardidlist',
            name='tcg_price_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 20, 21, 50, 51, 566950)),
        ),
        migrations.AlterField(
            model_name='quickresult',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 4, 20, 21, 50, 51, 567949)),
        ),
    ]
