# Generated by Django 3.1.7 on 2021-04-23 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0034_auto_20210420_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardidlist',
            name='tcg_price_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 20, 11, 25, 127281)),
        ),
        migrations.AlterField(
            model_name='quickresult',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 20, 11, 25, 127281)),
        ),
    ]
