# Generated by Django 3.1.7 on 2021-04-25 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0035_auto_20210422_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardidlist',
            name='tcg_price_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 22, 16, 7, 961750)),
        ),
        migrations.AlterField(
            model_name='quickresult',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 22, 16, 7, 962750)),
        ),
    ]
