# Generated by Django 3.1.7 on 2021-04-25 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0036_auto_20210424_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardidlist',
            name='color_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardidlist',
            name='tcg_price_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 18, 30, 11, 840057)),
        ),
        migrations.AlterField(
            model_name='quickresult',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 18, 30, 11, 840057)),
        ),
    ]
