# Generated by Django 3.1.7 on 2021-03-14 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(max_length=200)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('future', 'Future'), ('historic', 'Historic'), ('gladiator', 'Gladiator'), ('modern', 'Modern'), ('legacy', 'Legacy'), ('pauper', 'Pauper'), ('vintage', 'Vintage'), ('penny', 'Penny'), ('commander', 'Commander'), ('brawl', 'Brawl'), ('duel', 'Duel'), ('oldSchool', 'Old School'), ('premodern', 'Premodern')], default='Standard', max_length=25)),
                ('num_players', models.IntegerField(default=2)),
                ('starting_life', models.IntegerField(default=20)),
                ('min_deck_size', models.IntegerField(default=60)),
                ('max_deck_size', models.IntegerField(default=0)),
                ('side_board_size', models.IntegerField(default=15)),
                ('card_copy_limit', models.IntegerField(default=4)),
                ('has_commander', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Forfeit', 'Forfeit'), ('Playing', 'Playing'), ('Dead', 'Dead')], default='Playing', max_length=25)),
                ('avatar_img', models.CharField(max_length=200)),
                ('life', models.IntegerField()),
                ('acorn', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=0)),
                ('poison', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('storm', models.IntegerField(default=0)),
                ('clues', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('treasure', models.IntegerField(default=0)),
                ('commander_cost', models.CharField(default='{{},}', max_length=200)),
                ('commander_damage', models.CharField(default='{{},}', max_length=200)),
                ('monarch', models.BooleanField(default=False)),
                ('citys_blessing', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeCounter.game')),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeCounter.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_type', to='LifeCounter.gametype'),
        ),
    ]
