# Generated by Django 3.1.6 on 2021-02-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastCardImport', models.DateField()),
                ('lastRuleImport', models.DateField()),
                ('lastSymbolImport', models.DateField()),
            ],
        ),
    ]
