# Generated by Django 3.1.7 on 2021-03-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20210218_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='lastCardImport',
            new_name='last_card_import',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='lastRuleImport',
            new_name='last_rule_import',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='lastSymbolImport',
            new_name='last_symbol_import',
        ),
    ]
