# Generated by Django 3.1.7 on 2021-04-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20210412_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.IntegerField()),
                ('card_oracle', models.CharField(max_length=200)),
                ('card_name', models.CharField(max_length=200)),
                ('card_file', models.CharField(max_length=200, null=True)),
                ('card_search', models.CharField(max_length=2000)),
                ('quantity', models.IntegerField(default=0)),
                ('sideboard', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='deck',
            name='image_url',
            field=models.CharField(default='static/img/generic_box.png', max_length=200),
        ),
        migrations.DeleteModel(
            name='DeckCards',
        ),
    ]
