# Generated by Django 3.1.7 on 2021-04-15 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20210414_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='bearer_exp',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 23, 31, 34, 585181)),
        ),
    ]
