# Generated by Django 3.1.7 on 2021-04-18 01:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_auto_20210414_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=200)),
                ('oracle_id', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=500)),
                ('rarity', models.CharField(max_length=20)),
                ('set_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CardLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(max_length=30)),
                ('sides', models.IntegerField()),
                ('multi_face', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('set_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('released_at', models.DateField()),
                ('icon_svg_uri', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='settings',
            name='bearer_exp',
            field=models.DateField(default=datetime.datetime(2021, 4, 17, 21, 45, 13, 770587)),
        ),
        migrations.CreateModel(
            name='CardLegality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=30)),
                ('future', models.CharField(max_length=30)),
                ('historic', models.CharField(max_length=30)),
                ('gladiator', models.CharField(max_length=30)),
                ('modern', models.CharField(max_length=30)),
                ('legacy', models.CharField(max_length=30)),
                ('pauper', models.CharField(max_length=30)),
                ('vintage', models.CharField(max_length=30)),
                ('penny', models.CharField(max_length=30)),
                ('commander', models.CharField(max_length=30)),
                ('brawl', models.CharField(max_length=30)),
                ('duel', models.CharField(max_length=30)),
                ('old_school', models.CharField(max_length=30)),
                ('premodern', models.CharField(max_length=30)),
                ('card_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_card', to='Management.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('mana_cost', models.CharField(max_length=100)),
                ('loyalty', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=10)),
                ('toughness', models.CharField(max_length=10)),
                ('type_line', models.CharField(max_length=500)),
                ('color_id', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('flavor_text', models.CharField(max_length=500)),
                ('avatar_img', models.CharField(max_length=200)),
                ('first_face', models.BooleanField()),
                ('card_search', models.CharField(max_length=2000)),
                ('legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_legal', to='Management.cardlegality')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_layout', to='Management.cardlayout'),
        ),
        migrations.AddField(
            model_name='card',
            name='set_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_set', to='Management.cardset'),
        ),
    ]
