# Generated by Django 3.1.7 on 2021-04-19 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_auto_20210417_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='commander',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='bearer_exp',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 17, 17, 9, 632125)),
        ),
    ]
