# Generated by Django 3.1.7 on 2021-04-25 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0014_auto_20210422_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('card_name', models.CharField(max_length=100)),
                ('card_oracle', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('wish', models.BooleanField(default=False)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('color_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='settings',
            name='bearer_exp',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 22, 16, 7, 961750)),
        ),
    ]
