# Generated by Django 3.1.7 on 2021-04-25 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_auto_20210424_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='bearer_exp',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 18, 30, 11, 839057)),
        ),
    ]
