# Generated by Django 3.1.7 on 2021-02-28 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_pendingfriends_rejected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
