# Generated by Django 3.1.7 on 2021-03-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0006_delete_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatarImg',
            field=models.CharField(
                default='https://c1.scryfall.com/file/scryfall-cards/art_crop/front/0/2/0215cbbf-7bac-4ff7-bceb-23d728797848.jpg?1607534887',
                max_length=200),
            preserve_default=False,
        ),
    ]
