# Generated by Django 3.1.7 on 2021-03-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0009_auto_20210313_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='font_family',
            field=models.CharField(default='default_font', max_length=200),
        ),
    ]
