# Generated by Django 3.1.7 on 2021-03-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0010_userprofile_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='translate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
