# Generated by Django 3.1.7 on 2021-03-18 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0011_userprofile_translate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='usercards',
            old_name='cardID',
            new_name='card_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatarImg',
            new_name='avatar_img',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='cardView',
            new_name='card_view',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='deckView',
            new_name='deck_view',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profileView',
            new_name='profile_view',
        ),
    ]
