# Generated by Django 3.1.7 on 2021-03-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0012_auto_20210318_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercards',
            name='card_id',
        ),
        migrations.AddField(
            model_name='usercards',
            name='oracle_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
