# Generated by Django 3.1.7 on 2021-03-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_usercards_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCards',
        ),
    ]
