# Generated by Django 3.1.7 on 2021-03-23 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0005_auto_20210321_1820'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0015_delete_usercards'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracle_id', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=1000, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_obj', to='Collection.cardface')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
