# Generated by Django 3.1.7 on 2021-03-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0016_usercards'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercards',
            name='wish',
            field=models.BooleanField(default=False),
        ),
    ]
