# Generated by Django 3.1.7 on 2021-03-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0017_usercards_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercards',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
