# Generated by Django 3.1.7 on 2021-03-24 02:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0018_auto_20210323_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='eventDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='usercards',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
