# Generated by Django 3.1.7 on 2021-03-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_auto_20210323_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercards',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
