# Generated by Django 3.1.7 on 2021-03-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0020_auto_20210323_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='translate',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
