# Generated by Django 3.1.7 on 2021-03-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0021_auto_20210324_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='translate',
            field=models.CharField(default='notranslate', max_length=200, null=True),
        ),
    ]
