# Generated by Django 3.1.7 on 2021-04-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_userprofile_avatar_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_file',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
