# Generated by Django 3.1.7 on 2021-04-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_auto_20210331_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercards',
            old_name='oracle_id',
            new_name='card_oracle',
        ),
        migrations.RemoveField(
            model_name='usercards',
            name='card',
        ),
        migrations.AddField(
            model_name='usercards',
            name='card_search',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
