# Generated by Django 3.1.7 on 2021-04-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_auto_20210401_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercards',
            name='card_file',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usercards',
            name='card_mana',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercards',
            name='card_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
