# Generated by Django 3.1.7 on 2021-04-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_auto_20210401_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='deck_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_view',
            field=models.BooleanField(default=False),
        ),
    ]
