# Generated by Django 3.1.7 on 2021-04-21 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0028_auto_20210412_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_file',
        ),
    ]
